export * from './auditModule.service';
import { AuditModuleService } from './auditModule.service';
export * from './authModule.service';
import { AuthModuleService } from './authModule.service';
export * from './financialGovernanceModule.service';
import { FinancialGovernanceModuleService } from './financialGovernanceModule.service';
export * from './healthController.service';
import { HealthControllerService } from './healthController.service';
export * from './integrations.service';
import { IntegrationsService } from './integrations.service';
export * from './notificationModule.service';
import { NotificationModuleService } from './notificationModule.service';
export * from './projectModule.service';
import { ProjectModuleService } from './projectModule.service';
export * from './requisitionModule.service';
import { RequisitionModuleService } from './requisitionModule.service';
export * from './teamsModule.service';
import { TeamsModuleService } from './teamsModule.service';
export * from './userModule.service';
import { UserModuleService } from './userModule.service';
export * from './vendorModule.service';
import { VendorModuleService } from './vendorModule.service';
export * from './workflowModule.service';
import { WorkflowModuleService } from './workflowModule.service';
export const APIS = [AuditModuleService, AuthModuleService, FinancialGovernanceModuleService, HealthControllerService, IntegrationsService, NotificationModuleService, ProjectModuleService, RequisitionModuleService, TeamsModuleService, UserModuleService, VendorModuleService, WorkflowModuleService];
