/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserEditDto { 
    email?: string;
    name?: string;
    role?: UserEditDtoRoleEnum;
    teamId?: number;
    department?: UserEditDtoDepartmentEnum;
    isTeamLeader?: boolean;
}
export enum UserEditDtoRoleEnum {
    Requester = 'REQUESTER',
    ProcurementOfficer = 'PROCUREMENT_OFFICER',
    FinanceOfficer = 'FINANCE_OFFICER',
    Administrator = 'ADMINISTRATOR'
};
export enum UserEditDtoDepartmentEnum {
    It = 'IT',
    Rd = 'RD',
    Hr = 'HR',
    Sales = 'SALES',
    Legal = 'LEGAL'
};



