spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/veritas_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html    # Access via /api/v1/swagger-ui.html
    operations-sorter: alpha   # Sorts endpoints alphabetically
  api-docs:
    path: /api/v1/api.json
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:dev-only-secret-key-for-local-development-hs256}
    access-token-expiration: 1200000 # = 20 minutes