spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/veritas_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html    # Access via /api/v1/swagger-ui.html
    operations-sorter: alpha   # Sorts endpoints alphabetically
  api-docs:
    path: /api.json